name: Deploy Worker

on:
    push:
        branches:
            - main
    repository_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v3
              with:
                  run_install: true

            - name: Build & Deploy Worker
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
